### ISSUE TITLE
Vetev Ruby

### ISSUE THREAD

**Issue by Sedlo23** [Sedlo23/ZSWI_EEG#13]
pojmenovani ruby je podle me spatne pak bude tezky se v tom vyznat ....

**Comment by rubasj** [comment]
ok, no .. nenapadlo mě, jak geniálněji to pojmenovat, když je primárně určena pro mě... změním to 👍

**Comment by rubasj** [comment]
nějaká tip, jak to změnit mimo lokální uložiště?
